version: '2'
services:
  selenium:
    image: selenium/standalone-chrome-debug:3.141.59-vanadium
    ports:
      - "4444:4444"
      - "5900:5900"
    volumes:
      - ./spec/support/files:/shariasource/spec/support/files
  solr:
    command:
      - solr-precreate
      - default
      - /opt/solr/server/solr/configsets/sunspot
  corpusbuilder_background_jobs:
    command: ["/corpusbuilder/bin/app_ctl", "--jobs"]
    build: services/corpusbuilder
  corpusbuilder:
    command: ["/corpusbuilder/bin/app_ctl", "--init", "--migrate", "--seed", "--run"]
    build: services/corpusbuilder
    environment:
      - APP_ROOT=/corpusbuilder
      - BUNDLE_PATH=/bundle
      - BUNDLE_BIN=/bundle/bin
      - GEM_HOME=/bundle
      - CORPUS_BUILDER_HOST=http://corpusbuilder
      - CORPUS_BUILDER_PORT=3000
      - APP_DATABASE_NAME=corpus_builder
      - APP_DATABASE_USER=corpus_builder
      - APP_DATABASE_PASSWORD=zse45rdx
      - APP_DATABASE_URL=postgres_corpusbuilder
      - TESSDATA_PREFIX=/home/corpusbuilder/tesseract/tessdata
      - KRAKEN_DATA_PREFIX=/home/corpusbuilder/.config/kraken
      - RAILS_ENV=test
  postgres_shariasource:
    image: postgres:11
    volumes:
      - postgres_shariasource_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=zse45rdx
      - POSTGRES_USER=shariasource
      - POSTGRES_DB=shariasource
  shariasource:
    build: .
    hostname: shariasource
    links:
      - postgres_shariasource
      - corpusbuilder
      - solr
      - selenium
    environment:
      - APP_ROOT=/shariasource
      - APP_DATABASE_URL=postgres_shariasource
      - APP_DATABASE_NAME=shariasource
      - APP_DATABASE_USER=shariasource
      - APP_DATABASE_PASSWORD=zse45rdx
      - APP_PORT=3000
      - APP_SOLR_URL=solr
      - APP_SOLR_PORT=8983
      - CORPUS_BUILDER_API_URL=http://corpusbuilder:3000
      - CORPUS_BUILDER_PUBLIC_URL=http://corpusbuilder:3000
      - CORPUS_BUILDER_API_VERSION=1
      - CORPUS_BUILDER_SHARIA_SOURCE_APP_ID=00000000-0000-0000-0000-000000000000
      - CORPUS_BUILDER_SHARIA_SOURCE_TOKEN=$$2a$$08$$2rbUqU/KBR9ErNMlTZ29n.TWXe0a7OhwCbO25QQv.xpVuLS5r5SJ.
