default: &default
  app_id: <%= ENV['CORPUS_BUILDER_SHARIA_SOURCE_APP_ID'] %>
  secret: <%= ENV['CORPUS_BUILDER_SHARIA_SOURCE_SECRET'] %>
  host:   <%= ENV['CORPUS_BUILDER_HOST'] %>
  port:   <%= ENV['CORPUS_BUILDER_PORT'] %>

development:
  <<: *default

test:
  <<: *default
