production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/shariasource-production

development:
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO
    path: /solr/shariasource-development-1

test:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/shariasource-test-1
