production:
  solr:
    hostname: <%= ENV['APP_SOLR_URL'] %>
    port: <%= ENV['APP_SOLR_PORT'] %>
    log_level: WARNING
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: <%= ENV['APP_SOLR_URL'] %>
    port: <%= ENV['APP_SOLR_PORT'] %>
    log_level: INFO

test:
  solr:
    hostname: <%= ENV['APP_SOLR_URL'] %>
    port: <%= ENV['APP_SOLR_PORT'] %>
    log_level: WARNING
